### ISSUE TITLE
symbolBeforeCursorArray is null if previous symbol is whitespace or non alphanumeric

### ISSUE THREAD

**Issue by a-type** [bigeyex/brackets-wordhint#1]
While this doesn't generate a visible problem, if the debugger console is attached, null exceptions are constantly thrown on line [141 of main.js](https://github.com/bigeyex/brackets-wordhint/blob/master/main.js#L141), where you are indexing into `symbolBeforeCursorArray`. Regex returns null if there is no match, so the indexer will not work. Depending on how your extension functions, you might just need to skip that block if `symbolBeforeCursorArray` is null after the regex match.

**Comment by bigeyex** [comment]
Thanks for the feedback. The bug has been fixed.
