### ISSUE TITLE
Occasionally fail on word completion 

### ISSUE THREAD

**Issue by tgagor** [bigeyex/brackets-wordhint#2]
I'm using Brackets to write python code and word completion works great except that from time to time when I can't enter completed word by hitting Enter button. Word completion menu arrives, choosing words with up/down arrows works fine, hitting Enter to put suggested word works in 70% cases. It's so annoying when I hit Enter and get new line instead!
I'm using Gnome 3 on Ubuntu. Let me know if I could help you in any way.

**Comment by bigeyex** [comment]
I noticed that. It happens after several minutes not using word completion. I'm discussing the problem in the brackets-dev google group. 

Thanks for your support!

**Comment by bigeyex** [comment]
The issue disappeared, or hasn't happen for a long time after I fixed some minor bugs. I'm going to close this ticket now. Let me know if it happens again.
