### ISSUE TITLE
Question: what makes this extension?

### ISSUE THREAD

**Issue by anephew** [bigeyex/brackets-wordhint#3]
Hello. Sorry.  What makes this extension? What  means autocomplete? Any simple screencast/shot?
Thank you

**Comment by bigeyex** [comment]
It means it gives hint to the words appears in your current document.
e.g. If you used "MarbleBalls" before (maybe as a variable), 
the next time you type "Marb", "MarbleBalls" will appear in the list and will complete the whole word if you hit enter.

![screen shot 2014-10-10 at 9 00 24 pm](https://cloud.githubusercontent.com/assets/760670/4600899/0610ad78-50e2-11e4-8bf2-d3b262480b8b.png)
